### ISSUE TITLE
Error with Payload "Program too big for memory"

### ISSUE THREAD

**Issue by Dyotson** [0blio/caesarRAT#4]
Hi! So I finally made the server work (It was just a thing with mysql configuration, particular case).
The thing is I compiled the payload with PyInstaller, but everytime I try to execute it in a windows PC says on the cmd: "Program too big for memory"

**Comment by 0blio** [comment]
In order to make the payload executable on Windows you have to:

1. Generate the payload. Navigate to the `Client/` folder and: 
`python caesar.py <output> <your server ip/url>`

2. After that, since PyInstaller is not cross-compiler, you **must** move the generated payload on a Windows system and compile the payload on it:
* Install python 2
* `pip install requests`
* `pip install pyinstaller`
* `pyinstaller -F -w <your_generated_client_name>`

NB: For now the payload is written in python for testing purposes, in the future it will be translated in cpp / java to make the process of compiling it less intricate.

3. If all went the right way you should see your target writing `targets` in the main Caesar shell.

Let me know if you solve.
